### ISSUE TITLE
Twitch.tv

### ISSUE THREAD

**Issue by queuebit** [snarfed/huffduff-video#12]
When I try to `huffduff-video` a recorded [twitch page](http://www.twitch.tv/maxistentialist/v/31171595), I just get a huffduffer popup with no audio link. I couldn't tell by http://rg3.github.io/youtube-dl/supportedsites.html if it was supposed to be supported or not.

Let me know if I should open this issue on `youtube-dl` instead.

**Comment by snarfed** [comment]
hi! I'm guessing you used the huffduffer bookmarklet? it only knows to send a few sites to huffduff-video, eg YouTube and Vimeo. (cc @adactio) you'll need to use the bookmarklet on http://huffduff-video.snarfed.org/ for the rest. i was able to huffduff your twitch link with it: https://huffduffer.com/snarfed/286432

**Comment by queuebit** [comment]
That must be it. I have both bookmarklets and must have kept clicking the wrong one. Used the right one and it worked.

Thanks.
