### ISSUE TITLE
Vimeo no longer working

### ISSUE THREAD

**Issue by adactio** [snarfed/huffduff-video#13]
Parsing of Vimeo URLs seems to have stopped a few weeks back. I've tried with multiple Vimeo videos and keep getting the error:

"ERROR: No known codec found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output."

**Comment by snarfed** [comment]
oops, thanks for the report, and sorry for the breakage! looks like this is rg3/youtube-dl#7460 and/or rg3/youtube-dl#7601. i've upgraded youtube-dl from 2015.5.20 to 2015.12.23, and it's working again now.

**Comment by adactio** [comment]
:+1: Thank you!
