### ISSUE TITLE
ERROR: unable to write data: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by ghost** [snarfed/huffduff-video#15]
I'm getting the following error when trying to use huffduff-video bookmarklet. It seems to point to the server being out of space.

ERROR: unable to write data: [Errno 28] No space left on device

Thanks for your incredibly useful script.

**Comment by snarfed** [comment]
thanks for the report! and sorry for the breakage. fixed!

**Comment by queuebit** [comment]
I am getting the same error message when I try to huffduff-video something on Youtube.
