### ISSUE TITLE
ERROR: unable to write data: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by queuebit** [snarfed/huffduff-video#16]
I am getting the following error when trying to `huffduff-video` a youtube talk:

`ERROR: unable to write data: [Errno 28] No space left on device`

Thanks for the incredibly valueable script.

**Comment by snarfed** [comment]
ugh, sorry for the trouble. fixed! I'll keep this open until i have better disk cleanup in place.

**Comment by snarfed** [comment]
disk cleanup cron job runs daily now, and i've upgraded the disk from 8G to 20G, which should help. the IP address changed in the process, so some users won't be able to get to the site for the next few hrs until the new DNS propagates, but it's up at http://52.24.128.168/ .

thanks again @queuebit! tentatively closing.

**Comment by queuebit** [comment]
Thanks! I appreciate the help. Great tool.
