### ISSUE TITLE
I'm getting a Service Unavailable error

### ISSUE THREAD

**Issue by ghost** [snarfed/huffduff-video#19]
Here is the error I've been getting the past several days:

huffduff-video

Fetching https://www.youtube.com/watch?v=si-31hsxrGI&feature=em-uploademail ...
ERROR: Unable to download webpage: HTTP Error 503: Service Unavailable (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!

**Comment by snarfed** [comment]
ugh, sorry for the trouble @kketover! looks like youtube may be blocking or throttling some IPs in AWS, where huffduff-video runs. we're investigating in rg3/youtube-dl#9477.

**Comment by snarfed** [comment]
@kketover looks like it's ok now. youtube must have dropped the IP block. tentatively closing this, but i'll keep following the youtube-dl issue.
