### ISSUE TITLE
ssl issue on c-span.org

### ISSUE THREAD

**Issue by githubmarker** [snarfed/huffduff-video#20]
https://www.c-span.org/video/?191400-1/depth-francis-fukuyama
-->
http://huffduff-video.snarfed.org/get?url=https%3A%2F%2Fwww.c-span.org%2Fvideo%2F%3F191400-1%2Fdepth-francis-fukuyama

```
huffduff-video

Fetching https://www.c-span.org/video/?191400-1/depth-francis-fukuyama ...
ERROR: Unable to download webpage: (caused by URLError(SSLError(1, '_ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))

Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!
```

```
<!DOCTYPE html>
<html>
<head>
<title>huffduff-video</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="mobile-web-app-capable" content="yes">
</head>
<style> #progress span {display:none;}
        #progress span:last-of-type {display:inline;}
</style>
<body>
<h1><a href="http://huffduff-video.snarfed.org/" target="_blank">huffduff-video</a></h1>
<div id="progress">
Fetching https://www.c-span.org/video/?191400-1/depth-francis-fukuyama ...<br /><p>ERROR: Unable to download webpage: <urlopen error [Errno 1] _ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> (caused by URLError(SSLError(1, '_ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))</p>
Here are the <a href="http://rg3.github.io/youtube-dl/supportedsites.html">
supported sites</a>. If this site isn't supported, it may also post
its videos on YouTube. Try there!
</body>
</html>
```

C-Span is on the list of supported sites.

Using the current youtube-dl binary on windows the download proceeds properly.

youtube-dl.exe version 2016.05.16 (and [2016.09.04.1](https://yt-dl.org/downloads/2016.09.04.1/youtube-dl.exe)) from [the download page](http://rg3.github.io/youtube-dl/download.html),  the following command line successfully downloads an mp4 file::

`youtube-dl.exe https://www.c-span.org/video/?191400-1/depth-francis-fukuyama`

```
[CSpan] 191400: Downloading webpage
[CSpan] 171746: Downloading JSON metadata
[CSpan] 171746: Downloading XML
[download] Destination: In Depth with Francis Fukuyama-171746.mp4
[download]   3.0% of 1.18GiB at  8.00MiB/s ETA 02:25
```

I am not sure if this is a problem with the version of youtube-dl used as a library (it doesn't seem to be checked into the huffduff-video codebase) or some sort of SSL issue on the server executing the huffduff-video code.

**Comment by snarfed** [comment]
thanks for the report, and sorry for the trouble! looks like this is rg3/youtube-dl#10286. i've updated the system python and restarted the web server, but no luck, not sure why. hmm.

**Comment by snarfed** [comment]
upgraded requests and urllib3 and rebooted, but still no luck. :/

**Comment by snarfed** [comment]
looks like this was probably fixed in a recent youtube-dl release. i was able to convert that c-span video successfully earlier today: https://huffduffer.com/snarfed/408021
