### ISSUE TITLE
403 from s3 bucket

### ISSUE THREAD

**Issue by cmdln** [snarfed/huffduff-video#21]
The last couple of videos I snagged, cmdln at huff duff, return 403 when I try to download them.

**Comment by snarfed** [comment]
sorry for the trouble! i was able to download a few just now ok. S3 403s if the file doesn't exist. were the videos you tried over 30d old? ie from when you originally used huffduff-video on them? huffduff-video deletes files after 30d, so if so, that might be it.

**Comment by cmdln** [comment]
Thanks for the fast response. I added these files yesterday so they should still be within the 30d window.

**Comment by snarfed** [comment]
could you post an example url?

**Comment by cmdln** [comment]
https://huffduffer.com/cmdln/364067 That's an entry in my feed whose download link results in the 403.

**Comment by cmdln** [comment]
I just added another video, the file for that works fine.

**Comment by snarfed** [comment]
whoa, yeah, that URL is unhappy. looks like it downloaded from `https://www.oreilly.com/learning/how-do-you-subtract-two-dates-in-java`, but the huffduff-video URL is way different:

`https://huffduff-video.s3-us-west-2.amazonaws.com/kaltura_-1681692_0_mlq5pb0f_youtubedl_smuggle=%7B%22service_url%22%3A+%22https%3A%2F%2Fcdnapisec.kaltura.com%22%2C+%22source_url%22%3A+%22https%3A%2F%2Fwww.oreilly.com%2Flearning%2Fhow-do-you-subtract-two-`

i'm trying again, just to see.

**Comment by snarfed** [comment]
aha, i see. the retry ended up with the same S3 URL. the actual file in S3 is doubly url escaped though:

`https://s3-us-west-2.amazonaws.com/huffduff-video/kaltura_-1681692_0_mlq5pb0f_youtubedl_smuggle%3D%257B%2522service_url%2522%253A%2B%2522https%253A%252F%252Fcdnapisec.kaltura.com%2522%252C%2B%2522source_url%2522%253A%2B%2522https%253A%252F%252Fwww.oreilly.com%252Flearning%252Fhow-do-you-subtract-two-dates-in-java%2522%257D.mp3`

thanks for reporting! i'll fix this soon.

**Comment by cmdln** [comment]
Fantastic, thanks!

**Comment by snarfed** [comment]
actually, i was wrong, it wasn't the encoding. it's that the URL was cut off at `two-`, but the S3 file ends with the complete `two-dates-in-java%2522%257D.mp3`.

**Comment by snarfed** [comment]
huffduffer is truncating the URL we send it to 255 chars.

cc @adactio. this is probably rare, but still a surprise, and would break anyone else with long URLs too. maybe consider relaxing it on huffduffer's end?

otherwise, easy enough for us to do that truncating ahead of time, so we're not surprised and the S3 URL is preserved.

**Comment by adactio** [comment]
Yeah, the URL field is limited to 255 characters.

In retrospect, that was a _bad_ decision. :-(

I've doubled it. Hope that helps.

**Comment by snarfed** [comment]
tentatively closing. thanks all!
