### ISSUE TITLE
Soundcloud errors

### ISSUE THREAD

**Issue by adactio** [snarfed/huffduff-video#22]
Howdy!

It looks like anything on Soundcloud is no longer working with huffduff-video:

> ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Before I submit a bug report to youtube-dl I just wanted to check that huffduff-video was all up to date.

Cheers,

Jeremy

**Comment by snarfed** [comment]
hey jeremy, thanks for the report, and sorry for the trouble! looks like this was rg3/youtube-dl#11327. i've upgraded youtube-dl to 2016.12.15, which includes the fix, and soundcloud is working now. thanks again!

**Comment by adactio** [comment]
Sweet!!! Thank you!
