### ISSUE TITLE
Soundcloud audio is failing

### ISSUE THREAD

**Issue by albill** [snarfed/huffduff-video#23]
The site is failing to pull files from Soundcloud. I notice that yt-dl had an update recently. Maybe huffduff-video needs to update its version?

Error message:

huffduff-video
Fetching https://soundcloud.com/post-traditional-buddhism/111-imperfect-buddha-buddhism-goes-post-traditional ...

ERROR: Unable to download JSON metadata: HTTP Error 401: Unauthorized (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!

**Comment by snarfed** [comment]
thanks for the nudge! upgraded youtube-dl, looks like that fixed it.

**Comment by albill** [comment]
Yep, it is working now!
