### ISSUE TITLE
Provide form field for pasting a URL

### ISSUE THREAD

**Issue by aaronpk** [snarfed/huffduff-video#25]
It appears the only way to use this is via the bookmarklet, which means people who don't use bookmarks or the bookmark toolbar don't have a good way to use this. I was trying to walk someone through converting a video for huffduffer, and this was a stumbling block. It would have been clearer to explain to paste a Youtube URL into this app.

**Comment by snarfed** [comment]
yes! should be an easy addition to index.html alone.
