### ISSUE TITLE
Youtube fetching appears broken

### ISSUE THREAD

**Issue by albill** [snarfed/huffduff-video#26]
If you give a URL to a youtube video (such as https://www.youtube.com/watch?v=joSUFaLcKWc), you get:

huffduff-video
Fetching https://www.youtube.com/watch?v=joSUFaLcKWc ...

and then it stops. No further updates, no loading. The page load just finishes.

**Comment by snarfed** [comment]
fixed! thanks for reporting, and sorry for the breakage.
