### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by chausies** [snarfed/huffduff-video#27]
I tried to use the tool for a 50-minute YouTube video, and it errors out pretty badly without accomplishing anything. Any idea what's up?

Video: https://www.youtube.com/watch?v=KEt5_LELTd4

Error message:
Fetching https://www.youtube.com/watch?v=KEt5_LELTd4 ...

ERROR: Signature extraction failed: Traceback (most recent call last): File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 1070, in _decrypt_signature video_id, player_url, s File "/usr/local/lib/python2.7/site-packages/youtube_dl/extractor/youtube.py", line 958, in _extract_signature_function raise ExtractorError('Cannot identify player %r' % player_url) ExtractorError: Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output. (caused by ExtractorError(u"Cannot identify player u'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!

**Comment by snarfed** [comment]
thanks for filing, and sorry for the trouble! looks like youtube changed something. upgrading youtube-dl fixed it.
