### ISSUE TITLE
ERROR: unable to write data: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by chausies** [snarfed/huffduff-video#28]
Got this error while trying to get a simple 20-minute video.

Video:
https://www.youtube.com/watch?v=VPoX74kSHsE

**Comment by snarfed** [comment]
thanks for filing! fixed.

funny, someone plugged in https://ca.finance.yahoo.com/video/berkshire-hathaway-annual-meeting-155324347.html , which is massive, and we happily downloaded as much as we could until we filled up the disk. 😢

**Comment by chausies** [comment]
nice >.<.

Thanks a lot!
