### ISSUE TITLE
Failure to download

### ISSUE THREAD

**Issue by jeremycherfas** [snarfed/huffduff-video#29]
Trying to download from https://monocle.com/radio/shows/the-entrepreneurs/301/ I get this error:

"could not convert string to float: Unknown"

**Comment by snarfed** [comment]
huh, quite so. sorry about that!

I'm on vacation for the rest of this week, but I'll look when i get back.

**Comment by jeremycherfas** [comment]
No rush; sorry to disturb your vacation.

**Comment by snarfed** [comment]
fixed. thanks for reporting!
