### ISSUE TITLE
Cannot Huffduff Twitter Videos

### ISSUE THREAD

**Issue by ghost** [snarfed/huffduff-video#31]
I get the following error when trying to huffduff a twitter video:

huffduff-video

Fetching https://twitter.com/Seahawks/status/922246436753936386 ...
ERROR: Unable to extract guest token; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!

I have pulled a new copy of the bookmarklet just to make sure I have the latest. I have also tried pasting the link into the site and I get the same error.

**Comment by snarfed** [comment]
thanks for filing! looks like this is an open youtube-dl bug: rg3/youtube-dl#14197

**Comment by snarfed** [comment]
looks like they fixed it!
