### ISSUE TITLE
Vimeo?

### ISSUE THREAD

**Issue by edsu** [snarfed/huffduff-video#34]
My apologies if this isn't the right place to report this, but It appears that HuffDuffer bookmarlet is no longer working with Vimeo. Try this one:

https://vimeo.com/268653081

I see this in the popup window:

---

Fetching https://vimeo.com/268653081 ...

ERROR: Unable to extract info section (caused by ExtractorError(u'Unable to download webpage: HTTP Error 404: Not Found (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

---

Is it possible that youtube-dl needs to be updated where it is running?

**Comment by snarfed** [comment]
sorry for the trouble! yup, vimeo does seem unhappy right now. we've been discussing in #33. i'll repoen that.

**Comment by edsu** [comment]
Thanks!
