### ISSUE TITLE
The website seems to be completely down.

### ISSUE THREAD

**Issue by chausies** [snarfed/huffduff-video#36]
As of 5:36AM PT (9/2/2019), the website huffduff-video.snarfed.org is down. Not just from my end, but I also checked https://downforeveryoneorjustme.com/huffduff-video.snarfed.org, whom also say the website's down.

Perhaps it's just a temporary thing, but I thought I may as well report it here.

**Comment by snarfed** [comment]
sorry for the trouble, and thanks for the heads up! it was indeed temporary, it came back online around 5:50am.
