### ISSUE TITLE
Stuck on "Extracting audio"?

### ISSUE THREAD

**Issue by chausies** [snarfed/huffduff-video#38]
Using huffduffer, it seems to just hang and never get past "Extracting Audio (this can take a while)...". 
![huffduff](https://user-images.githubusercontent.com/2512400/70014514-e18d4700-152f-11ea-98d8-cfa3b4cda9b2.png)

I've let it run for over 30 minutes, and it doesn't complete. It's never been like this before. Any idea what's up?
Here's the vid I tried it on: https://www.youtube.com/watch?v=-yH6Z9m2vsg . Also tried another vid and it didn't work.

**Comment by snarfed** [comment]
hmm! sorry for the trouble. i see your attempts, and i haven't figured out why they hung yet, but i tried again just now after restarting apache (unrelated reasons), and i was able to huffduff that video successfully, so maybe transient.

**Comment by chausies** [comment]
Sorry.... When I try that vid now, it works immediately cuz it was already downloaded (presumably by you). But when I try another vid (https://www.youtube.com/watch?v=_-CqpTdhluw), it hangs in exactly the same way (on "Extracting Audio"). I can't imagine what the problem might be. It should be a server-side problem, but it sounds like it's only happening to me...?

**Comment by snarfed** [comment]
i have an odd lead on this. i recently noticed that comcast is blocking huffduff-video, maybe, for some reason. background: https://www.reddit.com/r/Comcast_Xfinity/comments/dblr1e/there_is_an_issue_with_your_connection/ . still investigating.

<img width="360" alt="image" src="https://user-images.githubusercontent.com/778068/70338667-310a9600-1802-11ea-8890-011de607cb32.png">

**Comment by chausies** [comment]
I have a feeling that that's not it. I'm using the Stanford University wifi, and I've also used a VPN, and the same problem occurs each time. Perhaps there's something odd happening with youtube-dl or ffmpeg? The other day, youtube-dl downloaded the video in the wrong format (mkv) for me for some reason....

**Comment by snarfed** [comment]
hey ajay, mind trying again? youtube started blocking huffduff-video, which may have been part of this. details in https://github.com/snarfed/huffduff-video/issues/37. i switched to a new IP address, which seems like it's fixed that at least.

**Comment by snarfed** [comment]
tentatively closing. feel free to reopen!
