### ISSUE TITLE
ERROR: AmS0KpQL1HU: YouTube said: Unable to extract video data

### ISSUE THREAD

**Issue by ghost** [snarfed/huffduff-video#39]
I have been getting this error all day today:
ERROR: AmS0KpQL1HU: YouTube said: Unable to extract video data
ERROR: nXdV46UD6Uo: YouTube said: Unable to extract video data

**Comment by snarfed** [comment]
hey, sorry for the trouble! looks like this is https://github.com/snarfed/huffduff-video/issues/37#issuecomment-534193970: youtube throttles and temporarily blocks huffduff-video sometimes. lots of background and details in that issue, feel free to subscribe to it for updates! unfortunately i don't have a straightforward fix yet though.
