### ISSUE TITLE
Unable to extract video data

### ISSUE THREAD

**Issue by jrsinclair** [snarfed/huffduff-video#40]
Currently Huffduff-video seems to be unable to download from YouTube:

Currently returning an error message like so:

> ### huffduff-video
> 
> Fetching https://www.youtube.com/watch?v=AnZ0uTOerUI ...
ERROR: AnZ0uTOerUI: YouTube said: Unable to extract video data
> 
> Here are the supported sites. If this site isn't supported, it may also post its videos on YouTube. Try there!

**Comment by snarfed** [comment]
hey james, sorry for the trouble! youtube started blocking huffduff-video recently, which is why you started seeing this error. details in https://github.com/snarfed/huffduff-video/issues/37 . i switched to a new IP address, which seems like it's fixed the problem for now. feel free to try again.

**Comment by jrsinclair** [comment]
Thanks @snarfed. Much appreciated.
