### ISSUE TITLE
Gets stuck at Fetching...  

### ISSUE THREAD

**Issue by dalesd** [snarfed/huffduff-video#41]
For the last several days I can't get huffduff-video to get beyond "Fetching".  All I get for output is, for example:  
Fetching https://www.youtube.com/watch?v=HcedcEr27ZU ...

I tried letting it go for hours and there's no sign of progress.  
I've tried it through the bookmarklet (my usual method) and the web interface.

**Comment by snarfed** [comment]
thanks for reporting, and sorry for the trouble! this was an IPv6 misconfiguration. i've fixed it, should be working now. thanks again!

**Comment by dalesd** [comment]
Thanks for fixing that so fast. That's amazing!
