### ISSUE TITLE
block crawlers/bots on backblaze, robots.txt or otherwise

### ISSUE THREAD

**Issue by snarfed** [snarfed/huffduff-video#43]
when we used AWS S3 to serve files, we got our own subdomain, eg https://huffduff-video.s3-us-west-2.amazonaws.com/ , so we could add and serve our own `/robots.txt` to block crawlers and other bots.

backblaze URLs don't give us our own subdomain, though. the bucket is in the path instead of the domain. example: https://f000.backblazeb2.com/file/huffduff-video/foo.mp3 . so we can't serve a `/robots.txt`. and i think we've started to see the crawlers and bots come back. April bandwidth usage was 4x March's, and May is on track to be a 5.5x increase over April, to 13TB!!! ugh.

<img width="648" alt="image" src="https://user-images.githubusercontent.com/778068/81114815-94930f80-8ed7-11ea-88c2-758c0cd91496.png">

number of files and file size has stayed constant.

<img width="651" alt="image" src="https://user-images.githubusercontent.com/778068/81115667-eee0a000-8ed8-11ea-9548-f10c43d62c76.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/778068/81115684-f6a04480-8ed8-11ea-93b6-3da482421154.png">

**Comment by queuebit** [comment]
Question "from afar":

Is there a way to use Cloudfront CDN and privatize the bucket?
- <https://www.backblaze.com/blog/backblaze-and-cloudflare-partner-to-provide-free-data-transfer/>
- <https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN>

Thanks for building / managing / supporting this great resource, `@`snarfed .

**Comment by snarfed** [comment]
> Is there a way to use Cloudfront CDN and privatize the bucket?

i wish! sadly Cloudflare is mainly intended for web sites, not audio. from https://www.cloudflare.com/terms/ :

> 2.8 Limitation on Serving Non-HTML Content
>
> The Service is offered primarily as a platform to cache and serve web pages and websites. Unless explicitly included as a part of a Paid Service purchased by you, you agree to use the Service solely for the purpose of serving web pages as viewed through a web browser or other functionally equivalent applications and rendering Hypertext Markup Language (HTML) or other functional equivalents. Use of the Service for serving video (unless purchased separately as a Paid Service) or a disproportionate percentage of pictures, audio files, or other non-HTML content, is prohibited.

their higher tier plans and add-ons do support streaming video and other use cases like this, but those are beyond huffduff-video's budget.

**Comment by queuebit** [comment]
Bummer.

Hopefully there is another "simple" solution, similar to your `/robots.txt` solutions with AWS s3.

**Comment by snarfed** [comment]
this turned out to be a fluke for just a short period in late april and early may. we're back on track for normal bandwidth usage in june, ~700GB/month.
<img width="655" alt="image" src="https://user-images.githubusercontent.com/778068/84423728-c5035300-abd3-11ea-9760-8179b3dfb82a.png">

**Comment by snarfed** [comment]
<img width="646" alt="image" src="https://user-images.githubusercontent.com/778068/86254310-7b6eae00-bb6a-11ea-9155-bc16753faa28.png">
