### ISSUE TITLE
Stuck on Opening Huffduffer dialog

### ISSUE THREAD

**Issue by jeremycherfas** [snarfed/huffduff-video#45]
That's it, really. Not the first time this has happened recently. From https://fieldlabearth.libsyn.com/sustainable-agriculture-programs-in-the-usa-and-eu-with-dr-scott-hutchins

The audio downloaded OK and then no dialog from Huffduffer.

I wonder, is it possible to show the url of the audio? Then I could add it to Huffduffer manually.

Thanks,

Jeremy

**Comment by snarfed** [comment]
Hmm! That's odd. Sorry for the trouble.

When I tried that URL just now, it opened the Huffduffer dialog ok. Screenshot below. Does it work for you now? If so, it may have been a transient huffduffer.com downtime or other issue, since huffduffer-video just redirects your browser there to open the dialog.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/778068/105879201-bb89f800-5fb6-11eb-8faf-48d58991b4c0.png">

**Comment by jeremycherfas** [comment]
I won’t try again as I have already saved it manually. 

Could it be a Js thing? I have a blocker on generally, but this seems to be a recent thing. 

I suppose I could look at the console to see whethe huffduffer is timing out. 

Thanks anyway. 

Jeremy

**Comment by snarfed** [comment]
Oh, no need to actually huffduff it, just see if it opens the dialog this time? My guess is it'll work now.

(and huffduff-video doesn't use any JS, at least not in the actual bookmarklet, so it shouldn't be that.)

**Comment by snarfed** [comment]
Also, huffduff-video caches its final MP3 files, including this one, so you won't have to wait for it to download and convert the video again. It will work (or not) immediately.

**Comment by snarfed** [comment]
@jeremycherfas any news here? Are you still seeing this problem?

**Comment by jeremycherfas** [comment]
Yes, I am still seeing it, but only in Firefox!
![huffduff](https://user-images.githubusercontent.com/4266172/106466833-21d1b780-649c-11eb-9a16-85ee2964e904.jpeg)

On a whim I tried Chrome, and that worked.
![huffduff-chrome](https://user-images.githubusercontent.com/4266172/106466912-3ada6880-649c-11eb-9322-053df913c140.jpeg)

I do have various blockers on FF and not on Chrome, but you said that's not likely to be it.

**Comment by snarfed** [comment]
Oh interesting! If it works for you in Chrome, then yes, it likely is one of your FF blockers. (I only said that this part of huffduff-video doesn't use JS; it's still very possible that blockers affect it somehow.)

**Comment by jeremycherfas** [comment]
I'll try and investigate further.

**Comment by snarfed** [comment]
@jeremycherfas just checking in here, did you ever figure this out?

**Comment by jeremycherfas** [comment]
Nope, I'm afraid not. Although the ability is super-useful, I don't use it very often so I have not felt the need to dig deeper.

**Comment by snarfed** [comment]
No worries! Feel free to reopen any time.
