### ISSUE TITLE
Switch to yt-dlp?

### ISSUE THREAD

**Issue by snarfed** [snarfed/huffduff-video#48]
[youtube-dl](https://github.com/ytdl-org/youtube-dl) is venerable and awesome and the workhorse behind huffduff-video, but its development progress may have stalled. It cut weekly releases for years, but the last release was 2 mos ago, 6/6/2021, and the two main maintainers now seem inactive on GitHub as a whole. Background in https://github.com/ytdl-org/youtube-dl/issues/29753 and https://github.com/ytdl-org/youtube-dl/issues/26462.

A couple active forks have popped up, https://github.com/yt-dlp/yt-dlp and https://github.com/blackjack4494/yt-dlc. Should we switch to one of them?

**Comment by nicolaasjan** [comment]
I've switched to [yt-dlp](https://github.com/yt-dlp/yt-dlp) and didn't regret it. :)
yt-dlc is also rather inactive.

**Comment by nicolaasjan** [comment]
@snarfed
Btw, when trying to go to https://huffduff-video.snarfed.org/ with Firefox,
I get:

> Secure connection failed
> 
> Error while connecting to huffduff-video.snarfed.org. SSL received a record that exceeded the maximum allowed length.
> 
> Error code: SSL_ERROR_RX_RECORD_TOO_LONG
> 
>The page you want to view cannot be displayed because the authenticity of the data received could not be verified.
>Please contact the website owners to inform them about this problem.

**Comment by snarfed** [comment]
@nicolaasjan true! huffduff-video doesn't currently support SSL. Let me know if you saw any https links to it anywhere, I can fix them!

**Comment by snarfed** [comment]
Ah, I see the one in the readme. Sorry! Will fix.

**Comment by nicolaasjan** [comment]
Works with http://huffduff-video.snarfed.org/.
But why don't you use https?

**Comment by nicolaasjan** [comment]
(offtopic)
With the "[Open With](https://addons.mozilla.org/en-US/firefox/addon/open-with/)" extension you can just make an entry in your right-click menu to download mp3 without needing any website.
I just point it to a shell-script (`youtube2mp3-downloader.sh`):

```bash
#!/bin/bash
#youtube to mp3 downloader
yt-dlp -o '~/Music/%(title)s.%(ext)s' -f bestaudio -x --audio-format mp3 --add-metadata --embed-thumbnail --audio-quality 0 $1
```

![screenshot1](https://user-images.githubusercontent.com/14093220/130117056-f584861b-e3c5-4ee2-a284-c4999a22ad59.png)

**Comment by snarfed** [comment]
> But why don't you use https?

No good reason, just haven't prioritized it yet, and Huffduffer profiles themselves are public, eg https://huffduffer.com/snarfed, so there's not a lot of privacy benefit.

> With the "Open With" extension you can just make an entry in your right-click menu to download mp3 without needing any website.

Yes! Most huffduff-video users do something similar with the bookmarklet shown on http://huffduff-video.snarfed.org/ . I only added the web form later.

**Comment by nicolaasjan** [comment]
> so there's not a lot of privacy benefit.

But...but... Then a 3 letter agency can see what mp3 you downloaded... :)

Anyway, for me the right-click on a video link is the easiest and fastest way (downloading straight to my PC).
And I usually download m4a, because the additional conversion to the outdated mp3 format involves quality loss.

**Comment by snarfed** [comment]
Youtube has been throttling youtube-dl for a while now. huffduff-video is only getting 40-80KB/s, which is...not ok. ☹️ https://github.com/ytdl-org/youtube-dl/issues/29326 , https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445 , https://twitter.com/mihai/status/1451975030686949380 . Time to prioritize this migration.
