### ISSUE TITLE
Updated graphics on pop-up is very nice

### ISSUE THREAD

**Issue by cameronj86** [snarfed/huffduff-video#50]
The progress bar looks a lot more modern and polished. Feels like I'm using a whole new product 😅

Random comment I'll be closing out shortly, but just wanted to praise the update

**Comment by snarfed** [comment]
Thanks for the kind words! That progress bar has actually been there for ~8y, #17, but it sometimes shows up immediately and sometimes not until a flash at the end. I don't fully understand how or when browsers decide to render bits of progressive output like huffduff-video uses. 🤷 Ah well.
