### ISSUE TITLE
Dockerfile misconfiguration - incorrect Python and b2sdk versions

### ISSUE THREAD

**Issue by ascandroli** [snarfed/huffduff-video#55]
There appears to be an issue with the current Dockerfile configuration, which prevents the project from running correctly inside Docker. I encountered two different errors when trying to run the project using Docker.

> ModuleNotFoundError: No module named 'boto'
> ModuleNotFoundError: No module named 'b2sdk._internal'

**Comment by ascandroli** [comment]
I am working on resolving the issue, I will send a PR shortly.

**Comment by snarfed** [comment]
Hey, thank you for doing this! Yeah as mentioned in the comments in that file, it's unused and unmaintained, so I'm not surprised it's rotted.

**Comment by snarfed** [comment]
Btw, are you planning to run your own instance of huffduff-video on an IP that YouTube hasn't blocked? Publicly? Privately? Something else?

I don't really plan to fight that arms race, so I may eventually turn down my instance at https://huffduff-video.snarfed.org/ . If I can point people to one you run that works, I'd love to!

**Comment by ascandroli** [comment]
It ran perfectly on my machine at home using a residential IP. My plan is to run it locally using my old Docker compose configuration. Might also make it a Home Assistant add-on so I can access it remotely, but for now, I'm good with just running it locally.
Sadly, I don't see a good way to make a service like this centralized anymore. YouTube is aggressively on the hunt for bots, so anything that's not normal consumer traffic gets blocked. Even the browser extensions are having issues for non-registered users.

**Comment by snarfed** [comment]
> Sadly, I don't see a good way to make a service like this centralized anymore. YouTube is aggressively on the hunt for bots, so anything that's not normal consumer traffic gets blocked.

Yeah, that makes sense, sadly. I guess I can switch this project to aim more at self hosting. Personally I've mostly switched to https://podqueue.fm/ , which is great, much more polished.

Anyway, fixed in #56. Thank you again for the contribution!
