### ISSUE TITLE
Downloads file, then nothing

### ISSUE THREAD

**Issue by ollisulopuisto** [snarfed/huffduff-video#9]
So this is an irritatingly generic bug, but on Chrome 43.0.2357.65 (64-bit) on OS X, the bookmarklet seems to download YouTube and Vimeo files just fine, but after that nothing happens. The regular huffduffer bookmarklet is working, so I'm signed in and all that.

How should I go about debugging this?

![nayttokuva 2015-5-25 kello 15 23 41](https://cloud.githubusercontent.com/assets/1051255/7797246/17c0c22a-02f2-11e5-82c6-edc1b10001ff.png)

**Comment by snarfed** [comment]
thanks for the report @ollisulopuisto! and sorry for the trouble. i suspect this is just (very) bad UI. when it prints "finished," it's lying. it's finished downloading from vimeo (or wherever), but it then needs to upload to S3.

i'll fix the UI problem. in the meantime, maybe try a smaller video and wait for a few minutes after "finished" to see if it eventually works?

**Comment by ollisulopuisto** [comment]
Okay, thanks.

I tried the script with a short YouTube video and pronto, everything worked.

I then tried that huge-ass Vimeo url referenced in the bug report and clicking on the bookmarklet resulted in a "Already downloaded" message and then redirected me to the Huffduffer bookmarking page proper.

So I guess everything's in order?

**Comment by snarfed** [comment]
thanks! yes, sounds like everything's in order except that bad UI. i'll fix that.
